sudo: required
os: linux
services:
  - docker

before_install:
  - docker pull vowpalwabbit/travis-base:20190202.1
script:
  - docker run -a STDOUT -v `pwd`:/vw -t vowpalwabbit/travis-base:20190202.1 /bin/bash -c "cd /vw && chmod +x ./build-linux.sh && ./build-linux.sh"

after_success:
  - docker run -e TRAVIS_JOB_ID -e TRAVIS_BRANCH -a STDOUT -v `pwd`:/vw -t vowpalwabbit/travis-base:20190202.1 /bin/bash -c "cd /vw && coveralls --include explore --include vowpalwabbit --gcov-options '\-lp'"
